image: python:3.13

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - linting
  - tests

default:
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python --version
    - python3 -m venv venv
    - source venv/bin/activate

formatting:
  stage: linting
  before_script:
    - pip install -r requirements.test.txt
  script:
    - codespell
    - ruff check

code quality:
  stage: linting
  before_script:
    - pip install -r requirements.test.txt
  script:
    - pylint ./custom_components/purpleair/
    - mypy ./custom_components/purpleair/
